### ISSUE TITLE
How to use results programatically

### ISSUE THREAD

**Issue by SilkAndSlug** [w3c/link-checker#21]
Is there a preferred way to script `checklink` to test for the presence or absence of errors? E.g. a CLI param to return 0 if no errors found or 2 if `checklink` completed successfully but found errors on the site.

I'm currently thinking to test for the `Error: ` string, but that feels ... fragile.

**Comment by dontcallmedom** [comment]
there is no such param at the moment unfortunately, but a patch to that effect would be welcomed (possibly as a default behavior rather than an optional one).

In the mean time, the way I've done it personally is to run it with the `-q -b` parameters and use the lack of output as a signal of success
